name: _error
timestamp: 1686729687
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1686729426
positions:
  top-a: 'Top A'
sections:
  top: Top
  navigation: Navigation
  hero: Hero
  slideshow: Slideshow
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  below: Below
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  jlimage:
    jlimage-8067: 'JL Image'
  content:
    system-content-2965: 'Page Content'
  jlheading:
    jlheading-2350: 'JL Heading'
  jlbutton:
    jlbutton-5036: 'JL Button'
  position:
    position-position-4359: 'Top A'
  jlnavbar:
    jlnavbar-8655: 'JL Navbar'
  jlfooterinfo:
    jlfooterinfo-7553: 'JL Footer Info'
  jlmodulepos:
    jlmodulepos-7234: 'JL Module Position'
  copyright:
    copyright-7447: Copyright
  branding:
    branding-4165: Branding
inherit:
  default:
    top: top
    navigation: navigation
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    position-position-4359: position-position-8328
    jlnavbar-8655: jlnavbar-2718
    jlfooterinfo-7553: jlfooterinfo-6993
    jlmodulepos-7234: jlmodulepos-1085
    copyright-7447: copyright-6042
    branding-4165: branding-9377
